---
- name: Install Nginx and Git (Ubuntu)
  become: true
  ansible.builtin.apt:
    name:
      - nginx
      - git
    state: present
    update_cache: true

- name: Create webroot directory for LightHouse
  become: true
  ansible.builtin.file:
    path: "{{ lighthouse_dir }}"
    state: directory
    mode: "0755"

- name: Clone LightHouse repository
  become: true
  ansible.builtin.git:
    repo: "https://github.com/VKCOM/lighthouse.git"
    dest: "{{ lighthouse_dir }}"
    version: "{{ lighthouse_version }}"

- name: Configure Nginx for LightHouse
  become: true
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: "/etc/nginx/sites-available/lighthouse"
    mode: "0644"
  notify: Restart Nginx service

- name: Enable LightHouse site in Nginx
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/lighthouse"
    dest: "/etc/nginx/sites-enabled/lighthouse"
    state: link
  notify: Restart Nginx service

- name: Remove default Nginx config
  become: true
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Restart Nginx service
